/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mindmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MindmapsController_findMine"];
        put?: never;
        post: operations["MindmapsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mindmaps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MindmapsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["MindmapsController_remove"];
        options?: never;
        head?: never;
        patch: operations["MindmapsController_update"];
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChatController_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeUserDto: {
            id: string;
            email: string;
            name: string;
        };
        MeResponseDto: {
            user: components["schemas"]["MeUserDto"];
        };
        MindmapNodeDto: {
            /**
             * @description Unique within the mindmap. The node with id "root" is the map's root and cannot be removed.
             * @example root
             */
            id: string;
            /** @example Backend */
            title: string;
            /**
             * @description Canvas position. The editor lays the tree out from scratch on load, so this is a hint about sibling order rather than a fixed coordinate.
             * @example 0
             */
            x: number;
            /** @example 0 */
            y: number;
        };
        MindmapEdgeDto: {
            /** @description Unique within the mindmap */
            id: string;
            /** @description Node id the edge starts from */
            source: string;
            /** @description Node id the edge points to. Direction is presentation only — the editor re-points edges parent to child when it lays the tree out. */
            target: string;
        };
        MindmapDto: {
            _id: string;
            title: string;
            ownerId: string;
            nodes: components["schemas"]["MindmapNodeDto"][];
            edges: components["schemas"]["MindmapEdgeDto"][];
            createdAt: string;
            updatedAt: string;
        };
        CreateMindmapDto: {
            /** @example My first mindmap */
            title: string;
        };
        UpdateMindmapDto: {
            /** @example Renamed mindmap */
            title?: string;
            /** @description Replaces every node. Ids must be unique and one of them must be "root". */
            nodes?: components["schemas"]["MindmapNodeDto"][];
            /** @description Replaces every edge. Ids must be unique, both endpoints must be nodes of this mindmap, and the result must stay a tree: no self-connections, no node pair connected twice, and no loops. Disconnected branches are allowed. */
            edges?: components["schemas"]["MindmapEdgeDto"][];
        };
        ChatRequestDto: {
            /** @description Chat session id from the AI SDK */
            id?: string;
            /** @description Id of the mindmap currently open in the canvas, used as conversation context */
            mindmapId?: string | null;
            /** @description AI SDK UIMessage array. See https://ai-sdk.dev — the shape is owned by the `ai` package and streamed back as a UI message event stream. */
            messages: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    MindmapsController_findMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MindmapDto"][];
                };
            };
        };
    };
    MindmapsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMindmapDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MindmapDto"];
                };
            };
            /** @description Body failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MindmapsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MindmapDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MindmapsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MindmapsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMindmapDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MindmapDto"];
                };
            };
            /** @description Body failed validation, or the patch would leave the mindmap with a graph that is not a tree */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequestDto"];
            };
        };
        responses: {
            /** @description AI SDK UI message event stream (SSE). Assistant text and mindmap tool calls arrive as streamed message parts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Body failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ANTHROPIC_API_KEY is not configured on the server */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
